### ISSUE TITLE
Document use with projects that don't need pyproject.toml

### ISSUE THREAD

**Issue by pfmoore** [uranusjr/pyem#3]
I've been using this project with ad-hoc data science analyses, where `pyproject.toml` isn't really needed, because there's no Python library or project to build.

It's easy to use, all you need to do is to create an empty `pyproject.toml` in the project root directory, but it's not immediately obvious that this is the right thing to do (and indeed I originally thought I should make this issue a request to use other ways of detecting the project root if `pyproject.toml` wasn't there, but I decided that was over-complicating the issue).

I suggest adding to the documentation a simple example of developing an adhoc script (or maybe a jupyter notebook). Something like:

> **To manage the environment for a data analysis**
>
> `mkdir my_project; cd my_project`
> `touch pyproject.toml # To tell pyem where the project root is`
> `pyem venv new 3.7`
> `pyem pip install jupyter-core pandas numpy matplotlib`
> `pyem jupyter notebook`

At the moment, I'm still experimenting with pyem for this sort of workflow, it's a minor convenience over using a "raw" virtualenv, but overall, I feel like it's useful, so I think it's worth treating this as a "first class" use case.

**Comment by uranusjr** [comment]
I’m still figuring that out myself as well. One possibility is to allow `pyem --project=. [other args]` to set the directory explicitly, but it’s still too awkward having to pass it for every command. Or maybe the `.venvs` directory can be used for look up instead, but I kind of worry that’s too implicit (since `.venvs` is hidden).

**Comment by pfmoore** [comment]
Maybe `pyem venv --project=<directory>` with the default being the directory containing `pyproject.toml` or the current directory if no `pyproject.toml` was found, and then other commands use `.venvs` on the basis that if you don't have a `.venvs` they won't work anyway.

You could add a `pyenv venv root` subcommand to show the project root (although it's not *really* correct to link it to the `venv` command, it may be better to do that than to reserve a second "special" command).

But I'm mostly just coming up with ideas here. As I say, an empty `pyproject.toml` is workable for now, so there's no real rush on making changes (and if you *are* thinking along the lines of improving the behaviour, it's probably not even worth documenting the workaround at this point).

**Comment by uranusjr** [comment]
Changed look up logic to:

* Takes a `--project` option before the command (e.g. `pyem --project ../other-project venv ...`); if this passed, use it as the project root, no questions asked (and error out if the directory does not exist)
* Look for a `.venvs` directory. Use its parent as the project root.
* If no `.venvs` directory is found in the tree, look for `pyproject.toml` instead (previous behaviour).

There two backwards incompatible cases: (assuming cwd is `inner`)

```
outer
|--- pyproject.toml
+--- inner
     |---- .venvs
     +---- (other stuff)
```

Previously the project root would be `outer`, but now it’d be `inner`.

```
outer
|--- .venvs
+--- inner
     |---- pyproject.toml
     +---- (other stuff)
```

Previously the project root would be `inner`, but now it’d be `outer`.

I kind of feel those are actually the better behaviour though, especially the latter example. Some projects would have multiple `pyproject.toml` in the repo (e.g. Flit), and usually they are intended to be installed in the same environment. Previously it’d be a pain to cd in and out of those nested projects, not the same `.venvs` container would be automatically reused without problems.
