### ISSUE TITLE
Generated sdist setup.py fails

### ISSUE THREAD

**Issue by jayvdb** [uranusjr/pyem#4]
0.4.4 sdist doesnt tell setuptools that the source is in src/pyem ; it looks for it in `pyem/` which doesnt exist.

c.f. https://build.opensuse.org/package/show/home:jayvdb:py-new/python-pyem

Also missing a LICENSE file

**Comment by uranusjr** [comment]
The project uses Flit for packaging, so it’s only natural that you couldnt gather the correct information with Setuptools. I am not familiar with openSUSE packaging, but some additional processing is probably needed.

**Comment by jayvdb** [comment]
This issue is about the sdist at https://files.pythonhosted.org/packages/1b/b5/bc320fac55f4699e6e4951c1d9ae9d45b213d676f551ae69b760f741c28f/pyem-0.4.4.tar.gz.  The setup.py in the tarball is broken.  I guess the generator is flit?  If so, the bug is in flit, or the local configuration which it uses.

**Comment by uranusjr** [comment]
Ah, makes sense. I’ll report this to upstream then.

**Comment by uranusjr** [comment]
Regardless of this upstream bug, the openSUSE build system would be better off to rely on [PEP 517](https://www.python.org/dev/peps/pep-0517/) instead of this setup.py file (which is only meant for compatibility with legacy setups that can’t be updated).

**Comment by uranusjr** [comment]
I published a beta release (0.5.0b2) with Flit patched. Could you verify whether it works?

**Comment by jayvdb** [comment]
Still broken.  And still doesnt contain a `LICENSE` file.
```console
[   13s] /usr/bin/python3 setup.py build '--executable=/usr/bin/python3 -s'
[   13s] running build
[   13s] running build_py
[   13s] /usr/lib64/python3.7/distutils/dist.py:274: UserWarning: Unknown distribution option: 'extras_require'
[   13s]   warnings.warn(msg)
[   13s] /usr/lib64/python3.7/distutils/dist.py:274: UserWarning: Unknown distribution option: 'entry_points'
[   13s]   warnings.warn(msg)
[   13s] /usr/lib64/python3.7/distutils/dist.py:274: UserWarning: Unknown distribution option: 'python_requires'
[   13s]   warnings.warn(msg)
[   13s] error: package directory 'pyem' does not exist
[   13s] error: Bad exit status from /var/tmp/rpm-tmp.vFb5Oq (%build)
```

**Comment by jayvdb** [comment]
fwiw, I suggest you use dephell to generate the `setup.py`.  That works quite reliably for packages using a `src/` subdirectory.

**Comment by jayvdb** [comment]
Does the Debian or Fedora or any distro use PEP 517 build system?

**Comment by uranusjr** [comment]
FWIW I don’t even *want* to generate that setup.py; Flit generates it for me, and there’s no way to turn it off. I don’t know how well PEP 517 is supported in various Linux distribution packaging communities (and don’t really care TBH).

**Comment by jayvdb** [comment]
afaik, PEP 517 isnt supported at all, by any major distro (maybe Arch?), but maybe that has changed in the last few months.

**Comment by jayvdb** [comment]
Maybe dont upload an sdist if you dont care about distros.

**Comment by uranusjr** [comment]
I don’t think I need permissions from you to upload *totally valid* Python sdists to a *Python* package index. The world doesn’t revolve around your precious Linux distro.
